name: CyberClinic Standalone Application

services:

  build_windows:
    image: dockurr/windows
    volumes:
      - ./src:/shared
    command: ["pip", "install", "-U", "pyinstaller"]
    
  build_macos:
    image: dockurr/macos
    command: ["pip", "install", "-U", "pyinstaller"]

  build_linux:
    image: ubuntu
    volumes:
      - ./src:/src
    command: ["pip", "install", "-U", "pyinstaller"]